export const categories = [
  "Limpieza de Hogar y Oficinas",
  "Música y DJ para Eventos",
  "Asesoría Legal y Tributaria",
  "Diseño Gráfico y Logos",
  "Cocina Casera y Catering",
  "Fotografía y Video",
  "Transporte y Mudanzas",
  "Belleza y Maquillaje a Domicilio",
  "Clases Particulares",
  "Artesanías y Productos Hechos a Mano",
  "Cuidado Holístico y Bienestar",
  "Marketing Digital y Redes Sociales",
  "Desarrollo Web y Tiendas Online",
  "Edición de Video y Contenido Audiovisual",
  "Asistente Virtual y Soporte Administrativo",
  "Redacción de Contenidos y Copywriting",
  "Reparaciones y Mantenimiento del Hogar",
  "Clases de Idiomas y Tutorías Online",
  "Diseño de Interiores y Arquitectura",
  "Gestión de Eventos y Organización de Fiestas"
] as const

export const categoryEmojis: Record<string, string> = {
  "Limpieza de Hogar y Oficinas": "🧹",
  "Música y DJ para Eventos": "🎧",
  "Asesoría Legal y Tributaria": "⚖️",
  "Diseño Gráfico y Logos": "🖼️",
  "Cocina Casera y Catering": "🍲",
  "Fotografía y Video": "📸",
  "Transporte y Mudanzas": "🚚",
  "Belleza y Maquillaje a Domicilio": "💄",
  "Clases Particulares": "📚",
  "Artesanías y Productos Hechos a Mano": "🧶",
  "Cuidado Holístico y Bienestar": "🧘",
  "Marketing Digital y Redes Sociales": "📱",
  "Desarrollo Web y Tiendas Online": "💻",
  "Edición de Video y Contenido Audiovisual": "🎥",
  "Asistente Virtual y Soporte Administrativo": "📋",
  "Redacción de Contenidos y Copywriting": "✍️",
  "Reparaciones y Mantenimiento del Hogar": "🔧",
  "Clases de Idiomas y Tutorías Online": "🗣️",
  "Diseño de Interiores y Arquitectura": "🏠",
  "Gestión de Eventos y Organización de Fiestas": "🎉",
}
