import { NextResponse } from 'next/server'
import { requireAdminFromDb } from '@/lib/admin-auth'
import { prisma } from '@/lib/prisma'
import { devLog, toPrismaJsonField } from '@/lib/utils'
import type { Prisma } from '@prisma/client'

export async function GET(request: Request) {
  const session = await requireAdminFromDb()
  if (!session) {
    return NextResponse.json({ error: 'No autorizado' }, { status: 403 })
  }

  const url = new URL(request.url)
  const page = Math.max(1, parseInt(url.searchParams.get('page') || '1', 10))
  const limit = Math.min(100, Math.max(5, parseInt(url.searchParams.get('limit') || '20', 10)))
  const skip = (page - 1) * limit
  const view = url.searchParams.get('view') || 'referrers'

  try {
    if (view === 'sellers') {
      // Sellers view: show ALL sellers with their referral attribution data (referredBy + commissions generated for their referrer)
      const total = await prisma.user.count({ where: { role: 'seller' } })
      const sellers = await prisma.user.findMany({
        where: { role: 'seller' },
        select: {
          id: true,
          name: true,
          email: true,
          businessName: true,
          createdAt: true,
          referredById: true,
          referredBy: {
            select: { id: true, name: true, email: true }
          }
        },
        orderBy: { createdAt: 'desc' },
        skip,
        take: limit,
      })

      const sellerIds = sellers.map((s: { id: string }) => s.id)

      // Compute referral commissions generated by each of these sellers (earnings to their referrers)
      const earningsForSellers = await prisma.referralEarning.findMany({
        where: {
          order: { sellerId: { in: sellerIds } }
        },
        select: {
          amount: true,
          status: true,
          order: { select: { sellerId: true } }
        }
      })

      const genMap = new Map<string, { total: number; pending: number; paid: number }>()
      earningsForSellers.forEach((e: { amount: number | null; status: string; order: { sellerId: string } | null }) => {
        const sid = e.order?.sellerId
        if (!sid) return
        const cur = genMap.get(sid) || { total: 0, pending: 0, paid: 0 }
        cur.total += (e.amount || 0)
        if (e.status === 'Pending' || e.status === 'Requested') {
          cur.pending += (e.amount || 0)
        } else if (e.status === 'Paid') {
          cur.paid += (e.amount || 0)
        }
        genMap.set(sid, cur)
      })

      const result = sellers.map((s: (typeof sellers)[number]) => ({
        seller: {
          id: s.id,
          name: s.name || s.email || 'Vendedor',
          email: s.email || '',
          businessName: s.businessName || null,
        },
        referredBy: s.referredBy ? {
          id: s.referredBy.id,
          name: s.referredBy.name || s.referredBy.email || '',
          email: s.referredBy.email || '',
        } : null,
        joined: s.createdAt,
        totalReferralGenerated: genMap.get(s.id)?.total || 0,
        pendingReferral: genMap.get(s.id)?.pending || 0,
        paidReferral: genMap.get(s.id)?.paid || 0,
        referredById: s.referredById || null,
      }))

      // Sort sellers with pending first, then by total generated
      result.sort((a: { pendingReferral: number; totalReferralGenerated: number }, b: { pendingReferral: number; totalReferralGenerated: number }) => (b.pendingReferral - a.pendingReferral) || (b.totalReferralGenerated - a.totalReferralGenerated))

      const totalPages = Math.ceil(total / limit) || 1
      return NextResponse.json({
        data: result,
        pagination: { page, limit, total, totalPages, hasNext: page < totalPages, hasPrev: page > 1 }
      })
    }

    // Default: referrers view (used by admin/referrals legacy + admin/payouts for pending referral commissions)
    // Get referrers with earnings (grouped) - paginate at referrer level
    const earnings = await prisma.referralEarning.groupBy({
      by: ['referrerId'],
      _sum: { amount: true },
      _count: { id: true },
    })

    const allReferrerIds = earnings.map((e: { referrerId: string }) => e.referrerId)
    const total = allReferrerIds.length
    const paginatedIds = allReferrerIds.slice(skip, skip + limit)

    const users = await prisma.user.findMany({
      where: { id: { in: paginatedIds } },
      select: { id: true, name: true, email: true, customReferralRate: true }
    })

    const { getPlatformConfig } = await import('@/lib/prisma');
    const config = await getPlatformConfig()
    const globalRate = config?.referralCommissionRate ?? 0.05

    // Count referred users per referrer (only for current page ids)
    const referredCounts = await prisma.user.groupBy({
      by: ['referredById'],
      _count: { id: true },
      where: { referredById: { in: paginatedIds } }
    })

    const referredCountMap = new Map(referredCounts.map((r: { referredById: string | null; _count: { id: number } }) => [r.referredById, r._count.id]))

    // Fetch earnings only for current page referrers (reduces N+1 data)
    const pageEarnings = await prisma.referralEarning.findMany({
      where: { referrerId: { in: paginatedIds } },
      select: { referrerId: true, amount: true, status: true }
    })

    const pendingMap = new Map<string, number>()
    const paidMap = new Map<string, number>()
    const requestedMap = new Map<string, number>()

    pageEarnings.forEach((e: { referrerId: string; amount: number; status: string }) => {
      if (e.status === 'Pending') {
        pendingMap.set(e.referrerId, (pendingMap.get(e.referrerId) || 0) + e.amount)
      } else if (e.status === 'Paid') {
        paidMap.set(e.referrerId, (paidMap.get(e.referrerId) || 0) + e.amount)
      } else if (e.status === 'Requested') {
        requestedMap.set(e.referrerId, (requestedMap.get(e.referrerId) || 0) + e.amount)
      }
    })

    // Build only for the paginated referrers (from group earnings that match page)
    const pageEarningsGroup = earnings.filter((e: { referrerId: string }) => paginatedIds.includes(e.referrerId))
    const result = pageEarningsGroup.map((e: { referrerId: string; _sum: { amount: number | null }; _count: { id: number } }) => {
      const user = users.find((u: { id: string }) => u.id === e.referrerId)
      const customRate = user?.customReferralRate
      const effectiveRate = customRate != null ? customRate : globalRate
      const rid = e.referrerId

      return {
        referrer: {
          id: rid,
          name: user?.name || user?.email || 'Usuario',
          email: user?.email || '',
        },
        referredCount: referredCountMap.get(rid) || 0,
        totalGenerated: e._sum.amount || 0,
        earningsCount: e._count.id,
        effectiveReferralRate: effectiveRate,
        customReferralRate: customRate,
        // Payout relevant
        pendingPayout: (pendingMap.get(rid) || 0) + (requestedMap.get(rid) || 0),
        paidOut: paidMap.get(rid) || 0,
        requestedAmount: requestedMap.get(rid) || 0,
      }
    })

    // Sort by pending payout descending for easy payout management
    result.sort((a: { pendingPayout: number }, b: { pendingPayout: number }) => b.pendingPayout - a.pendingPayout)

    const totalPages = Math.ceil(total / limit) || 1
    return NextResponse.json({
      data: result,
      pagination: { page, limit, total, totalPages, hasNext: page < totalPages, hasPrev: page > 1 }
    })
  } catch (error) {
    devLog('Admin referrals error:', error)
    return NextResponse.json({ error: 'Error al obtener datos' }, { status: 500 })
  }
}

// PATCH to mark earnings as Paid (admin action for payouts)
export async function PATCH(request: Request) {
  const session = await requireAdminFromDb()
  if (!session) {
    return NextResponse.json({ error: 'No autorizado' }, { status: 403 })
  }

  try {
    const { referrerId } = await request.json()
    if (!referrerId) {
      return NextResponse.json({ error: 'referrerId requerido' }, { status: 400 })
    }

    // tx for payout mark + audit
    const result = await prisma.$transaction(async (tx: Prisma.TransactionClient) => {
      const upd = await tx.referralEarning.updateMany({
        where: { referrerId, status: { in: ['Pending', 'Requested'] } },
        data: { status: 'Paid' }
      })
      await tx.auditLog.create({
        data: {
          performedById: session?.user?.id ?? undefined,
          action: 'REFERRAL_PAYOUT_MARKED_PAID',
          targetType: 'User',
          targetId: referrerId,
          details: toPrismaJsonField({ count: upd.count }),
        },
      })
      return upd
    })

    return NextResponse.json({ success: true, updated: result.count })
  } catch (error) {
    console.error('Mark payout paid error:', error)
    return NextResponse.json({ error: 'Error al marcar como pagado' }, { status: 500 })
  }
}
